#!/bin/bash

# options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xter

./configure \
    --prefix=/usr \
    --enable-256-color \
    --enable-combining \
    --enable-fading \
    --enable-font-styles \
    --enable-mousewheel \
    --enable-perl \
    --enable-pixbuf \
    --enable-pointer-blank \
    --enable-slipwheeling \
    --enable-smart-resize \
    --enable-text-blink \
    --enable-transparency \
    --enable-unicode3 \
    --enable-utmp \
    --enable-warnings \
    --enable-wtmp \
    --enable-xft \
    --enable-xft \
    --enable-xim \
    --enable-xterm-scroll

# `configure' configures this package to adapt to many kinds of systems.
# 
# Usage: ./configure [OPTION]... [VAR=VALUE]...
# 
# To assign environment variables (e.g., CC, CFLAGS...), specify them as
# VAR=VALUE.  See below for descriptions of some of the useful variables.
# 
# Defaults for the options are specified in brackets.
# 
# Configuration:
#   -h, --help              display this help and exit
#       --help=short        display options specific to this package
#       --help=recursive    display the short help of all the included packages
#   -V, --version           display version information and exit
#   -q, --quiet, --silent   do not print `checking ...' messages
#       --cache-file=FILE   cache test results in FILE [disabled]
#   -C, --config-cache      alias for `--cache-file=config.cache'
#   -n, --no-create         do not create output files
#       --srcdir=DIR        find the sources in DIR [configure dir or `..']
# 
# Installation directories:
#   --prefix=PREFIX         install architecture-independent files in PREFIX
#                           [/usr/local]
#   --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
#                           [PREFIX]
# 
# By default, `make install' will install all the files in
# `/usr/local/bin', `/usr/local/lib' etc.  You can specify
# an installation prefix other than `/usr/local' using `--prefix',
# for instance `--prefix=$HOME'.
# 
# For better control, use the options below.
# 
# Fine tuning of the installation directories:
#   --bindir=DIR            user executables [EPREFIX/bin]
#   --sbindir=DIR           system admin executables [EPREFIX/sbin]
#   --libexecdir=DIR        program executables [EPREFIX/libexec]
#   --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
#   --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
#   --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
#   --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
#   --libdir=DIR            object code libraries [EPREFIX/lib]
#   --includedir=DIR        C header files [PREFIX/include]
#   --oldincludedir=DIR     C header files for non-gcc [/usr/include]
#   --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
#   --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
#   --infodir=DIR           info documentation [DATAROOTDIR/info]
#   --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
#   --mandir=DIR            man documentation [DATAROOTDIR/man]
#   --docdir=DIR            documentation root [DATAROOTDIR/doc/PACKAGE]
#   --htmldir=DIR           html documentation [DOCDIR]
#   --dvidir=DIR            dvi documentation [DOCDIR]
#   --pdfdir=DIR            pdf documentation [DOCDIR]
#   --psdir=DIR             ps documentation [DOCDIR]
# 
# X features:
#   --x-includes=DIR    X include files are in DIR
#   --x-libraries=DIR   X library files are in DIR
# 
# System types:
#   --build=BUILD     configure for building on BUILD [guessed]
#   --host=HOST       cross-compile to build programs to run on HOST [BUILD]
# 
# Optional Features:
#   --disable-option-checking  ignore unrecognized --enable/--with options
#   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
#   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
#   --enable-everything     enable standard non-multichoice features
#                           NOTE: this option is order dependent
#   --enable-assert         enable assertions
#   --enable-warnings       turn on g++ warnings
#   --enable-256-color      enable 256-color support
#   --enable-unicode3       use 21 instead of 16 bits to represent unicode characters
#   --enable-combining      enable composition of base and combining characters
#   --enable-xft            enable xft support on systems that have it
#   --enable-font-styles    enable bold and italic support
#   --enable-pixbuf         enable integration with gdk-pixbuf for background images
#   --enable-startup-notification  enable freedesktop startup notification support
#   --enable-transparency   enable transparent backgrounds
#   --enable-fading         enable colors fading when off focus
#   --enable-rxvt-scroll    enable rxvt style scrollbar
#   --enable-next-scroll    enable NeXT style scrollbar
#   --enable-xterm-scroll   enable Xterm style scrollbar
#   --enable-perl           enable embedded perl interpreter
#   --enable-xim            XIM (X Input Method) protocol support
#   --disable-backspace-key disable handling of the backspace key
#   --disable-delete-key    disable handling of the delete key
#   --disable-resources     disable all resource checking
#   --enable-8bitctrls      enable 8 bit control sequences (not recommended)
#   --enable-fallback[=CLASS] fall back on CLASS resources in addition to URxvt ones (default: Rxvt)
#   --disable-swapscreen    disable swap screen support
#   --enable-iso14755       enable support for extended ISO 14755 modes
#   --enable-frills         enable support for rarely used features
#   --enable-keepscrolling  enable continual scrolling on scrollbar arrow press
#   --enable-selectionscrolling  enable scrolling during selections
#   --enable-mousewheel     enable scrolling via mouse wheel or buttons 4 & 5
#   --enable-slipwheeling   enable slip wheel scrolling (requires --enable-mousewheel)
#   --enable-smart-resize   enable smart growth/shrink behaviour
#   --enable-text-blink     enable blinking text
#   --enable-pointer-blank  enable pointer blanking when typing or inactive
#   --enable-utmp           enable utmp (utmpx) support
#   --enable-wtmp           enable wtmp (wtmpx) support (requires --enable-utmp)
#   --enable-lastlog        enable lastlog support (requires --enable-utmp)
# 
# Optional Packages:
#   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
#   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
#   --with-codesets=CS,...  compile in additional codesets (jp,jp_ext,kr,zh,zh_ext,all)
#   --with-res-name=NAME    use this as default resource name (default: urxvt)
#   --with-res-class=CLASS  use this as the resource class (default: URxvt)
#   --with-name=NAME        set the basename for the installed binaries (default: urxvt)
#   --with-term=NAME        set the terminal to NAME (default: rxvt)
#   --with-terminfo=PATH    set the path to the terminfo tree to PATH
#   --with-x                use the X Window System
# 
# Some influential environment variables:
#   CC          C compiler command
#   CFLAGS      C compiler flags
#   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
#               nonstandard directory <lib dir>
#   LIBS        libraries to pass to the linker, e.g. -l<library>
#   CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
#               you have headers in a nonstandard directory <include dir>
#   CXX         C++ compiler command
#   CXXFLAGS    C++ compiler flags
#   CPP         C preprocessor
#   CXXCPP      C++ preprocessor
#   XMKMF       Path to xmkmf, Makefile generator for X Window System
# 
# Use these variables to override the choices made by `configure' or to help
# it to find libraries and programs with nonstandard names/locations.
# 
# Report bugs to the package provider.
